config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help", to: "static_pages#help", as: :help_page
  get "about", to: "static_pages#about", as: :about_page
  devise_for :users
  resources :categories, only: :index
  resources :lessons, except: :delete
  resources :users, only: [:update, :edit]

  namespace :admin do
    resources :dashbroad, only: :index
    resources :categories
    resources :words
  end
  resources :words, only: :index
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def about
  end
  
end

app/views/static_pages/about.html.erb
<h1>About</h1>

app/views/static_pages/help.html.erb
<div class="container">
  <h1>Under-Contruction</h1>
</div>

app/views/static_pages/home.html.erb
<% if current_user.present? %>
  <div class="col-md-2 text-center">
    <%= image_tag current_user.avatar.url, class: "img-responsive" %>
    <p><%= t(:name, scope: :home) %>: <strong><%= current_user.name || t(:no_name, scope: :home) %></strong></p>
    <%= link_to t(:edit, scope: :home), edit_user_path(current_user), method: :GET, class: "btn btn-primary" %>
    <p><%= t(:learned, scope: :home) %> <%= current_user.lessons.sum_learned %> <%= t(:word, scope: :home) %></p>
  </div>
  <div class="col-md-10">
    <div class="row">
      <div class="col-md-6 text-center">
        <%= link_to t(:word, scope: :home), words_path, class: "btn btn-primary" %>
      </div>
      <div class="col-md-6 text-center">
        <%= link_to t(:lesson, scope: :home), categories_path(), method: :GET, class: "btn btn-primary" %>
      </div>
    </div>
    <div class="row">
      <p><strong><%= t(:activities, scope: :home) %></strong></p>
      <hr/>
      <% current_user.lessons.each do |lesson| %>
        <div class="row">
          <div class="col-md-2"><%= image_tag current_user.avatar.url, class: "img-responsive icon" %></div>
          <div class="col-md-10">
            <p class="learned"><%= t(:learned, scope: :home) %> <%= lesson.answers.learned.count %> <%= t(:word_in_lesson, scope: :home) %> "<%= lesson.category.title %>" - (<%= lesson.created_at.strftime("%F") %>)</p>
          </div>
        </div>  
      <% end %>
    </div>
  </div>
<% else %>
  <h1><%= t(:home_page, scope: :home) %></h1>
<% end %>