config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help", to: "static_pages#help", as: :help_page
  get "about", to: "static_pages#about", as: :about_page
  devise_for :users
  resources :categories, only: :index
  resources :lessons, except: :delete
  resources :users, only: [:update, :edit]

  namespace :admin do
    resources :dashbroad, only: :index
    resources :categories
    resources :words
  end
  resources :words, only: :index
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :lesson_words
  has_many :lessons, through: :lesson_words
  accepts_nested_attributes_for :answers

  validates :content, presence: true
  validates :category, presence: true
  
  self.per_page = Settings.will_per

  scope :get_all, ->user{}
  scope :get_learned, ->user{joins(:lesson_words, :lessons).where(lessons: {user_id: user.id}).uniq
                                                           .where.not(lesson_words: {answer_id: nil})}
  scope :get_not_learned, ->user{joins(:lesson_words, :lessons).where(lessons: {user_id: user.id}).uniq
                                                               .where(lesson_words:{answer_id: nil})}

  STATUS = ["all", "learned", "not_learned"]
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :set_word, except: :index

  def index
    @categories = Category.all
    @words = Word.paginate page: params[:page]
    @word = Word.new
    @word.answers.build
  end

  def create
    word = Word.new word_params
    if word.save
      flash[:notice] = t :create_success, scope: :admin_words
      redirect_to admin_word_path word
    else
      flash[:notice] = t :create_failed, scope: :admin_words
      redirect_to :back
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    if @word.update_attributes word_params
      flash[:notice] = t :update_success, scope: :admin_words
      redirect_to admin_words_path
    else
      flash[:notice] = t :update_failed, scope: :admin_words
      redirect_to :back
    end
  end

  def destroy
    if @word.destroy
      flash[:notice] = t :delete_success, scope: :admin_words
      redirect_to admin_words_path
    else
      flash[:notice] = t :delete_failed, scope: :admin_words
      redirect_to :back
    end
  end

  private
  def word_params
    params.require(:word).permit :category_id, :content, answers_attributes: [:id, :content, :is_true, :_destroy]
  end

  def set_word
    @word = Word.find params[:id] rescue nil
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @categories = Category.all
    if params[:category_id]
      category = Category.find params[:category_id] rescue nil
      status = params[:state]
      @words = category.words.send "get_#{status}", current_user
    else
      @words = Category.first.words
    end
  end
end

app/views/admin/words/_answer_fields.html.erb
<div class="form-group">
  <label><%= t(:content, scope: :admin_answers) %></label><br/>
  <%= f.text_field :content, autocomplete: "off", class: "form-control", placeholder: t(:p_content, scope: :admin_words) %>
  <%= f.radio_button :is_true, true %> <%= f.label :is_true, t(:is_true, scope: :admin_words) %>
  <%= link_to_remove_fields t(:remove), f %>
</div>

app/views/admin/words/_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= t :create_words, scope: :admin_words %></h4>
      </div>
      <%= form_for [:admin, @word], html: {method: :POST} do |f| %>
        <div class="modal-body">
          <label><%= t :category, scope: :admin_words %></label><br/>
          <div class="form-group">
            <%= f.select :category_id, @categories.collect{|item| [item.title, item.id]}, class: "col-md-4 col-md-offset-3"%>
          </div>
          <label><%= t :content, scope: :admin_words %></label><br/>
          <div class="form-group">
            <%= f.text_field :content, autocomplete: "off", class: "form-control", placeholder: t(:p_content, scope: :admin_words) %>
          </div>
          <%= f.fields_for :answers do |builder| %>
            <%= render "answer_fields", f: builder %>
          <% end %>
          <div class="add-answers"></div>
          <p><%= link_to_add_fields t(:add_answer), f, :answers %></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal"><%= t :close, scope: :admin_categories %></button>
          <%= f.submit t(:save, scope: :admin_words), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/words/_word.html.erb
<tr>
  <td><%= word.content %></td>
  <td>
    <%= link_to t(:show, scope: :admin_words), admin_word_path(word), method: :GET, class: "btn btn-success pull-right" %>
  </td>
  <td>
    <%= link_to t(:edit, scope: :admin_words), edit_admin_word_path(word), method: :GET, class: "btn btn-primary pull-right" %>
  </td>
  <td>
    <%= link_to t(:delete, scope: :admin_words), admin_word_path(word), method: :DELETE, class: "btn btn-danger pull-right", "data-confirm": t(:confirm) %>
  </td>
</tr>

app/views/admin/words/edit.html.erb
<p><strong><%= t :edit_words, scope: :admin_words %></strong></p>
<%= form_for [:admin, @word], html: {method: :PUT} do |f| %>
  <div class="modal-body">
    <label><%= t(:category, scope: :admin_words) %></label><br/>
    <div class="form-group">
      <%= f.select :category_id, @categories.collect{|item| [item.title,item.id]}, class: "col-md-4 col-md-offset-3"%>
    </div>
    <label><%= t :content, scope: :admin_categories %></label><br/>
    <div class="form-group">
      <%= f.text_field :content, autocomplete: "off", class: "form-control", placeholder: t(:p_content, scope: :admin_categories) %>
    </div>
    <%= f.fields_for :answers do |ff| %>
      <label><%= t :content, scope: :admin_answers %></label><br/>
      <div class="form-group">
        <%= ff.text_field :content, autocomplete: "off", class: "form-control", placeholder: t(:p_content, scope: :admin_words) %>
        <%= ff.radio_button :is_true, true %> <%= f.label :is_true,  t(:is_true, scope: :admin_words) %>
      </div>
    <% end %>
  </div>
  <div class="modal-footer">
    <%= f.submit t(:save, scope: :admin_categories), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/words/index.html.erb
<%= render partial: "modal" %>
<table class="table">
  <tr>
    <th><%= t :content, scope: :admin_words %></th>
    <th></th>
    <th></th>
    <th>
      <button type="button" class="btn btn-info pull-right" data-toggle="modal" data-target="#myModal">
        <%= t :new, scope: :admin_words %>
      </button>
    </th>
  </tr>
  <%= render partial: "word", collection: @words %>
</table>
<%= will_paginate @words %>

app/views/admin/words/show.html.erb
<div class="row">
  <p><strong><%= t :words_information, scope: :admin_words %></strong></p>
  <p><strong><%= t :content, scope: :admin_words %>:</strong> <%= @word.content %></p>
  <% @word.answers.each_with_index do |answer, index| %>
    <p><strong><%= t :answer, scope: :admin_answers %>-<%= index %>:</strong> <%= answer.content %></p>
  <% end %>
</div>