config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help", to: "static_pages#help", as: :help_page
  get "about", to: "static_pages#about", as: :about_page
  devise_for :users
  resources :categories, only: :index
  resources :lessons, except: :delete
  resources :users, only: [:update, :edit]

  namespace :admin do
    resources :dashbroad, only: :index
    resources :categories
    resources :words
  end
  resources :words, only: :index
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :words
  has_many :lessons
  accepts_nested_attributes_for :words

  validates :title, presence: true
  
  self.per_page = Settings.will_per
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_categories, except: :index

  def index
    @categories = Category.paginate page: params[:page]
    @category = Category.new
  end

  def create
    category = Category.new category_params
    if category.save
      flash[:success] = t :create_success, scope: :admin_categories
      redirect_to admin_categories_path
    else
      flash[:danger] = t :create_failed, scope: :admin_categories
      redirect_to admin_categories_path
    end
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t :update_success, scope: :admin_categories
      redirect_to admin_categories_path
    else
      flash[:danger] = t :update_failed, scope: :admin_categories
      redirect_to admin_categories_path
    end
  end

  def destroy
    if @category && @category.destroy
      flash[:success] = t :delete_success, scope: :admin_categories
      redirect_to admin_categories_path
    else
      flash[:danger] = t :delete_failed, scope: :admin_categories
      redirect_to admin_categories_path
    end
  end

  private
  def category_params
    params.require(:category).permit :title, :description, :content
  end

  def set_categories
    @category = Category.find params[:id] rescue nil
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.paginate page: params[:page], per_page: 3
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= category.title %></td>
  <td><%= category.description %></td>
  <td><%= category.content %></td>
  <td>
  <%= link_to t(:show, scope: :admin_categories), admin_category_path(category), method: :GET, class: "btn btn-success pull-right" %>
  </td>
  <td>
  <%= link_to t(:edit, scope: :admin_categories), edit_admin_category_path(category), method: :GET, class: "btn btn-primary pull-right" %>
  </td>
  <td>
  <%= link_to t(:delete, scope: :admin_categories), admin_category_path(category), method: :DELETE, class: "btn btn-danger pull-right", "data-confirm": t(:confirm) %>
  </td>
</tr>

app/views/admin/categories/_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= t :create_categories, scope: :admin_categories %></h4>
      </div>
      <%= form_for [:admin, @category], html: {method: :POST} do |f| %>
        <div class="modal-body">
          <label><%= t :title, scope: :admin_categories %></label><br/>
          <div class="form-group">
            <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: t(:p_title, scope: :admin_categories) %>
          </div>
          <label><%= t :description, scope: :admin_categories %></label><br/>
          <div class="form-group">
            <%= f.text_field :description, autofocus: true, class: "form-control", placeholder: t(:p_description, scope: :admin_categories) %>
          </div>
          <label><%= t :content, scope: :admin_categories %></label><br/>
          <div class="form-group">
            <%= f.text_field :content, autocomplete: "off", class: "form-control", placeholder: t(:p_content, scope: :admin_categories) %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal"><%= t :close, scope: :admin_categories %></button>
          <%= f.submit t(:save, scope: :admin_categories), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<p><strong><%= t :edit_categories, scope: :admin_categories %></strong></p>
<%= form_for [:admin, @category], html: {method: :PUT} do |f| %>
  <div class="modal-body">
    <label><%= t :title, scope: :admin_categories %></label><br/>
    <div class="form-group">
      <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: t(:p_title, scope: :admin_categories) %>
    </div>
    <label><%= t :description, scope: :admin_categories %></label><br/>
    <div class="form-group">
      <%= f.text_field :description, autofocus: true, class: "form-control", placeholder: t(:p_description, scope: :admin_categories) %>
    </div>
    <label><%= t :content, scope: :admin_categories %></label><br/>
    <div class="form-group">
      <%= f.text_field :content, autocomplete: "off", class: "form-control", placeholder: t(:p_content, scope: :admin_categories) %>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit t(:save, scope: :admin_categories), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/categories/index.html.erb
<%= render partial: "modal" %>
<table class="table">
  <tr>
    <th><%= t :title, scope: :admin_categories %></th>
    <th><%= t :description, scope: :admin_categories %></th>
    <th><%= t :content, scope: :admin_categories %></th>
    <th></th>
    <th></th>
    <th>
      <button type="button" class="btn btn-info pull-right" data-toggle="modal" data-target="#myModal">
        <%= t :new, scope: :admin_categories %>
      </button>
    </th>
  </tr>
  <%= render partial: "category", collection: @categories %>
</table>
<%= will_paginate @categories %>

app/views/admin/categories/show.html.erb
<div class="row">
  <p><strong><%= t :categories_information, scope: :admin_categories %></strong></p>
  <p><strong><%= t :title, scope: :admin_categories %>:</strong> <%= @category.title %></p>
  <p><strong><%= t :description, scope: :admin_categories %>:</strong> <%= @category.description %></p>
  <p><strong><%= t :content, scope: :admin_categories %>:</strong> <%= @category.content %></p>
</div>