config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help", to: "static_pages#help", as: :help_page
  get "about", to: "static_pages#about", as: :about_page
  devise_for :users
  resources :categories, only: :index
  resources :lessons, except: :delete
  resources :users, only: [:update, :edit]

  namespace :admin do
    resources :dashbroad, only: :index
    resources :categories
    resources :words
  end
  resources :words, only: :index
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li>Copyright&2015</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-custom">
  <div class="container">
    <%= link_to I18n.t(:project_name), '/', id: "logo" %> 
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(:menu_home), '/' %></li>
        <li><%= link_to t(:menu_help), help_page_path() %></li>
        <li><%= link_to t(:menu_about), about_page_path() %></li>

        <% if user_signed_in? %>
          <li><%= link_to t(:menu_logout), destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to t(:menu_sign_up), new_user_registration_path %></li>
          <li><%= link_to t(:menu_login), new_user_session_path %></li>
        <% end %>

       </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fels_62</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>  
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    
    <%= yield %>
    <%= render "layouts/footer" %>
  </div>
</body>
</html>